services:
  rabbitmq:
    container_name: 'book-rabbitmq'
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    container_name: 'book-redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes