chat.model=gemini

spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Gemini Developer API (use API key)
spring.ai.google.genai.api-key=${GEMINI-API-KEY}

# Vertex AI (use Google Cloud credentials instead of API key)
# spring.ai.google.genai.project-id=reading-list-450715
# spring.ai.google.genai.location=europe-west4
