spring.application.name=ai-practice
spring.config.import=optional:file:.env[.properties]

chat.model=gemini
#chat.model=ollama

# Gemini Developer API (use API key)
spring.ai.google.genai.api-key=${GEMINI-API-KEY}

# Vertex AI (use Google Cloud credentials instead of API key)
# spring.ai.google.genai.project-id=reading-list-450715
# spring.ai.google.genai.location=europe-west4

spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:latest

books.api.key=${BOOKS-API-KEY}
#books.provider=google
#books.provider=openLibrary
books.provider=wikiBooks
